import torch

BATCH_SIZE = 64 # how many independent sequences will we process in parallel?
BLOCK_SIZE = 128 # what is the maximum context length for predictions?
MAX_ITERS = 5000
EVAL_INTERVAL = 500
LEARNING_RATE = 3e-4
EVAL_ITERS = 200
N_EMBD = 384
N_HEAD = 6
N_LAYER = 6
DROPOUT = 0.0
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

DATA_PER_CATEGORY = 5_000
QUERY_BATCH_SIZE = 200
NUM_BATCHES = DATA_PER_CATEGORY // QUERY_BATCH_SIZE

# Morphological transformations
SINGULAR_TO_PLURAL = "singular_to_plural"
PRESENT_TENSE_TO_PAST_TENSE = "present_tense_to_past_tense"
BASE_CASE_TO_THIRD_PERSON_SINGULAR = "base_case_to_third_person_singular"
SINGULAR_POSSESSIVE_TO_PLURAL_POSSESSIVE = "singular_possessive_to_plural_possessive"
COMPARATIVE_ADJECTIVE_TO_SUPERLATIVE_ADJECTIVE = "comparative_adjective_to_superlative_adjective"
VERB_TO_PROGRESSIVE_VERB = "verb_to_progressive_verb"
VERB_TO_DERIVED_AGENTIVE = "verb_to_derived_agentive"
BASE_CASE_TO_DIMINUITIVE = "base_case_to_diminuitive"
ADJECTIVE_TO_ADVERB = "adjective_to_adverb"
VERB_TO_GERUND = "verb_to_gerund"
NOUN_TO_ADJECTIVE = "noun_to_adjective"
POSITIVE_TO_NEGATIVE_PREFIX = "positive_to_negative_prefix"
VERB_TO_NOUN = "verb_to_noun"
PRESENT_TENSE_TO_FUTURE_TENSE = "present_tense_to_future_tense"
CARDINAL_TO_ORDINAL = "cardinal_to_ordinal"
ADJECTIVE_TO_NOUN = "adjective_to_noun"
BASE_TO_REFLEXIVE_PRONOUN = "base_to_reflexive_pronoun"
BASE_TO_PAST_PARTICIPLE = "base_to_past_participle"
SIMPLE_PAST_TO_PAST_PERFECT = "simple_past_to_past_perfect"
AFFIRMATIVE_TO_NEGATIVE = "affirmative_to_negative"
CONCRETE_TO_ABSTRACT_NOUN = "concrete_to_abstract_noun"

DATA_CATEGORIES = [
    SINGULAR_TO_PLURAL,
    PRESENT_TENSE_TO_PAST_TENSE,
    BASE_CASE_TO_THIRD_PERSON_SINGULAR,
    SINGULAR_POSSESSIVE_TO_PLURAL_POSSESSIVE,
    COMPARATIVE_ADJECTIVE_TO_SUPERLATIVE_ADJECTIVE,
    VERB_TO_PROGRESSIVE_VERB,
    VERB_TO_DERIVED_AGENTIVE,
    BASE_CASE_TO_DIMINUITIVE,
    ADJECTIVE_TO_ADVERB,
    VERB_TO_GERUND,
    NOUN_TO_ADJECTIVE,
    POSITIVE_TO_NEGATIVE_PREFIX,
    VERB_TO_NOUN,
    PRESENT_TENSE_TO_FUTURE_TENSE,
    CARDINAL_TO_ORDINAL,
    ADJECTIVE_TO_NOUN,
    BASE_TO_PAST_PARTICIPLE,
    SIMPLE_PAST_TO_PAST_PERFECT,
    AFFIRMATIVE_TO_NEGATIVE,
]

TRAIN_DATA_CATEGORIES = [
    SINGULAR_TO_PLURAL,
    PRESENT_TENSE_TO_PAST_TENSE,
    BASE_CASE_TO_THIRD_PERSON_SINGULAR,
    SINGULAR_POSSESSIVE_TO_PLURAL_POSSESSIVE,
    COMPARATIVE_ADJECTIVE_TO_SUPERLATIVE_ADJECTIVE,
    VERB_TO_PROGRESSIVE_VERB,
    VERB_TO_DERIVED_AGENTIVE,
    BASE_CASE_TO_DIMINUITIVE,
    ADJECTIVE_TO_ADVERB,
    VERB_TO_GERUND,
    NOUN_TO_ADJECTIVE,
    POSITIVE_TO_NEGATIVE_PREFIX,
    VERB_TO_NOUN,
    PRESENT_TENSE_TO_FUTURE_TENSE,
    CARDINAL_TO_ORDINAL,
    ADJECTIVE_TO_NOUN,
]

VAL_DATA_CATEGORIES = [
    SINGULAR_TO_PLURAL,
    PRESENT_TENSE_TO_PAST_TENSE,
    BASE_CASE_TO_THIRD_PERSON_SINGULAR,
    SINGULAR_POSSESSIVE_TO_PLURAL_POSSESSIVE,
    COMPARATIVE_ADJECTIVE_TO_SUPERLATIVE_ADJECTIVE,
    VERB_TO_PROGRESSIVE_VERB,
    VERB_TO_DERIVED_AGENTIVE,
    BASE_CASE_TO_DIMINUITIVE,
    ADJECTIVE_TO_ADVERB,
    VERB_TO_GERUND,
    NOUN_TO_ADJECTIVE,
    POSITIVE_TO_NEGATIVE_PREFIX,
    VERB_TO_NOUN,
    PRESENT_TENSE_TO_FUTURE_TENSE,
    CARDINAL_TO_ORDINAL,
    ADJECTIVE_TO_NOUN,
    BASE_TO_PAST_PARTICIPLE,
    SIMPLE_PAST_TO_PAST_PERFECT,
    AFFIRMATIVE_TO_NEGATIVE,
]